stage: 1
type_vocab_size: 8
VERBOSE: true


WEIGHTS: 
    model_weight: ''
    bert_weight: ''
    pretrained_2d: True


DATA:
    NAME: ActivityNet
    DATA_DIR: ./data/tsg/ActivityNet
    BATCH_SIZE_per_gpu: 4
    NUM_WORKERS: 0
    PIN_MEMORY: True

    VIS_INPUT_TYPE: c3d
    NO_VAL: False
    NUM_SAMPLE_CLIPS: 256
    TARGET_STRIDE: 4
    NORMALIZE: True
    RANDOM_SAMPLING: False

    DATASET_train: {
            'name': 'ActNetRetDataset-train',
            'type': 'ActNetDataset',
            'metadata_path': 'data/tsg/ActivityNet/train.json',
            'video_path': 'data/tsg/ActivityNet/actnet_video_1fps'
        }
    DATASET_trainval: {
            'name': 'ActNetDataset-val',
            'type': 'ActNetDataset',
            'metadata_path': 'data/tsg/ActivityNet/val.jsonl',
            'video_path': 'data/tsg/ActivityNet/actnet_video_1fps'
        }
    DATASET_test: {
            'name': 'ActNetDataset-test',
            'type': 'ActNetDataset',
            'metadata_path': 'data/tsg/ActivityNet/test.json',
            'video_path': 'data/tsg/ActivityNet/actnet_video_1fps'
        }
    DATASET_val: {
            'name': 'ActNetDataset-val',
            'type': 'ActNetDataset',
            'metadata_path': 'data/tsg/ActivityNet/val.jsonl',
            'video_path': 'data/tsg/ActivityNet/actnet_video_1fps'
        }


TRAINING:
    EPOCHS: 100
    LOSS:   {
        'loss_name': 'BCERescaleLoss',
        'min_iou': 0.5,
        'max_iou': 1.0,
        'bias': 0.0
    }
    WARMUP_EPOCHS: 5
    WARMUP_LR: 0.
    LR_SCHEDULER: {
        'NAME': 'ReduceLROnPlateau',
        'FACTOR': 0.8,
        'PATIENCE': 20,
        'CONTINUE': false
        }
    CLIP_GRAD: true
    weight_decay: 0.0000

    save_dir: "outputs/tsg/tan/actnet_2D-TAN-conv"
    checkpoint_step: 3000
    save_step: 1000
    print_step: 50
    eval_step: 200


TEST:
  RECALL: 1,5
  TIOU: 0.3,0.5,0.7
  EVAL_TRAIN: False
  NMS_THRESH: 0.5


TAN:
  FRAME_MODULE:
    NAME: FrameAvgPool
    PARAMS:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
      STRIDE: 4

  PROP_MODULE:
    NAME: SparsePropConv
    PARAMS:
      HIDDEN_SIZE: 512
      NUM_SCALE_LAYERS: [16,8,8]

  FUSION_MODULE:
    NAME: BaseFusion
    PARAMS:
      HIDDEN_SIZE: 512
      TXT_INPUT_SIZE: 300
      TXT_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False

  MAP_MODULE:
    NAME: MapConv
    PARAMS:
      INPUT_SIZE: 512
      HIDDEN_SIZES: [512, 512, 512, 512]
      KERNEL_SIZES: [9, 9, 9, 9]
      STRIDES: [1, 1, 1, 1]
      PADDINGS: [16, 0, 0, 0]
      DILATIONS: [1, 1, 1, 1]

  PRED_INPUT_SIZE: 512